# Use a imagem oficial do Node.js para construir o front-end
FROM node:20.17.0-alpine3.20 as build

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto
COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build

# Imagem para servir a aplicação
FROM node:20.17.0-alpine.20
WORKDIR /app
# Copie os arquivos construídos para o servidor Nginx
COPY --from=build /app ./

# Exponha a porta 80
EXPOSE 80

# Comando para iniciar o servidor
CMD ["npm", "start"]
