# Use a imagem oficial do Node.js para construir o front-end
FROM node:18 as build

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Imagem para servir a aplicação
FROM nginx:stable-alpine

# Copie os arquivos construídos para o servidor Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80

# Comando para iniciar o servidor
CMD ["nginx", "-g", "daemon off;"]
