# Use a imagem oficial do Node.js para construir o front-end
FROM node:20-alpine AS builder

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto
COPY package.json package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Imagem para servir a aplicação
FROM node:20-alpine AS runner
WORKDIR /app
# Copie os arquivos construídos para o servidor Nginx
COPY --from=builder /app ./

# Exponha a porta 3000
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]
