services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
    depends_on:
      - db
    networks:
      - app_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   enviroment:
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #     - NEXTAUTH_URL=${NEXTAUTH_URL}
  #   depends_on:
  #     - backend

volumes:
  db-data:

networks:
  app_network:
    driver: bridge