# Use a imagem oficial do .NET SDK para build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Defina o diretório de trabalho
WORKDIR /app

# Copie e restaure os arquivos do projeto
COPY *.csproj ./
RUN dotnet restore

# Copie o restante do código
COPY . ./

# Faça o build do projeto
RUN dotnet publish -c Release -o out -p:AssemblyName=UranusTask

# Imagem para execução
FROM build AS final

# Defina o diretório de trabalho
WORKDIR /app

# Copie o build para a imagem final
COPY --from=build /app/out .

# Exponha a porta 5000
EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000
# Comando para iniciar o servidor
ENTRYPOINT ["dotnet", "UranusTask.dll"]
